import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";


export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
function TopNav(){
  return (
    <nav className="flex items-center justify-between w-full h-16 bg-black p-4 text-xl font-bold border-b">
      <div className="flex items-center">CALCULATOR</div>
    </nav>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className={`flex flex-col gap-4`}>
      <TopNav/>
      {children}
      </body>
    </html>
  );
}
